import './global.css';
import { TopNav } from '../components';
import Providers from '../providers/Providers';

export const metadata = {
  title: 'Budget',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TopNav />
          <div className="m-1 sm:m-2 md:m-5 lg:m-10">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
